version: "3.9"

services:
  app:
    image: ghcr.io/kksseonn/catty-reminders:latest
    container_name: catty-reminders
    restart: unless-stopped
    ports:
      - "8181:8181"
    volumes:
      - catty_data:/catty-reminders-app/data
      - ./config.json:/catty-reminders-app/config.json:ro

volumes:
  catty_data: