name: CD

on:
  release:
    types: [ published ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/vm_key
          chmod 600 ~/.ssh/vm_key

      - name: Deploy using Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no \
              -o ConnectTimeout=15 \
              -i ~/.ssh/vm_key \
              -p 2451 \
              user@course.prafdin.ru "
            
            echo 'Logging in to GHCR...'
            echo '${{ secrets.GITHUB_TOKEN }}' | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            echo 'Pulling updated images...'
            docker compose -f ~/Desktop/lab1/catty-reminders-app/docker-compose.yaml pull

            echo 'Recreating stack...'
            docker compose -f ~/Desktop/lab1/catty-reminders-app/docker-compose.yaml up -d

            echo 'Cleaning unused images...'
            docker image prune -f

            echo 'Deployment complete!'
            docker compose -f ~/Desktop/lab1/catty-reminders-app/docker-compose.yaml ps
          "