name: CD

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/vm_key
          chmod 600 ~/.ssh/vm_key

      - name: Copy docker-compose and config.json to VM
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/vm_key -P 2451 docker-compose.yaml user@course.prafdin.ru:~/app/
          scp -o StrictHostKeyChecking=no -i ~/.ssh/vm_key -P 2451 config.json user@course.prafdin.ru:~/app/

      - name: Deploy with Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no \
              -o ConnectTimeout=15 \
              -i ~/.ssh/vm_key \
              -p 2451 \
              user@course.prafdin.ru "
      
              docker login ghcr.io -u ${{ github.actor }} -p ${{secrets.GITHUB_TOKEN}}

              cd ~/Desktop/lab1/catty-reminders-app || exit 1

              docker compose -f docker-compose.yml pull
              
              docker compose -f docker-compose.yml down || true

              docker compose -f docker-compose.yml up -d
            "